robot:
  lidar2robot_x: 0.345
  lidar2robot_y: 0.0
  lidar2robot_dis: 0.345
  lidar2robot_ang: 0.0
  lidar2robot_ang_x: 180.0

topic:
  odometry_topic: "/aft_mapped_to_init"
  cluster_topic: "/depth_clustering/clusters"

function:
  odometry_en: true
  cluster_en: false

data_process:
  delta_dis_threshold: 2.0
